#!/bin/bash
#
#  Copyright (c) 2022-2024, The OpenThread Authors.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the
#     names of its contributors may be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#

set -euxo pipefail

OTRFSIM_SRCDIR="$(pwd)"
OT_DIR=${OT_DIR:-../openthread}
readonly OTRFSIM_SRCDIR
readonly OT_DIR

# OpenThread options that are always added to build first. They can be overridden on the command line.
OT_OPTIONS=(
    "-DCMAKE_BUILD_TYPE=Debug"
    "-DOT_PLATFORM=external"
    "-DOT_FULL_LOGS=ON"
    "-DOT_VENDOR_NAME=OpenThread.io"
    "-DOT_VENDOR_MODEL=RFSIM-Node"
    "-DOT_VENDOR_SW_VERSION=2.0.0"
    "-DOT_JOINER=ON"
    "-DOT_COAP=ON"
    "-DOT_COAPS=ON"
    "-DOT_COMMISSIONER=ON"
    "-DOT_ECDSA=ON"
    "-DOT_NETDIAG_CLIENT=ON"
    "-DOT_MESH_DIAG=ON"
    "-DOT_SERVICE=ON"
    "-DOT_BLE_TCAT=ON"
)
readonly OT_OPTIONS

build()
{
    local builddir="${OT_CMAKE_BUILD_DIR:-build}"

    mkdir -p "${builddir}"
    cd "${builddir}"

    cmake -GNinja -DOT_COMPILE_WARNING_AS_ERROR=ON "$@" "${OTRFSIM_SRCDIR}"
    ninja -j7 ot-cli-ftd ot-cli-mtd ot-ncp-ftd ot-ncp-mtd ot-rcp

    cd "${OTRFSIM_SRCDIR}"
}

main()
{
    local options=()
    options+=("${OT_OPTIONS[@]}" "$@")
    build "${options[@]}"
}

main "$@"
