// Code generated by protoc-gen-go. DO NOT EDIT.
// source: visualize_grpc.proto

package visualize_grpc_pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OtDeviceRole int32

const (
	OtDeviceRole_OT_DEVICE_ROLE_DISABLED OtDeviceRole = 0
	OtDeviceRole_OT_DEVICE_ROLE_DETACHED OtDeviceRole = 1
	OtDeviceRole_OT_DEVICE_ROLE_CHILD    OtDeviceRole = 2
	OtDeviceRole_OT_DEVICE_ROLE_ROUTER   OtDeviceRole = 3
	OtDeviceRole_OT_DEVICE_ROLE_LEADER   OtDeviceRole = 4
)

var OtDeviceRole_name = map[int32]string{
	0: "OT_DEVICE_ROLE_DISABLED",
	1: "OT_DEVICE_ROLE_DETACHED",
	2: "OT_DEVICE_ROLE_CHILD",
	3: "OT_DEVICE_ROLE_ROUTER",
	4: "OT_DEVICE_ROLE_LEADER",
}

var OtDeviceRole_value = map[string]int32{
	"OT_DEVICE_ROLE_DISABLED": 0,
	"OT_DEVICE_ROLE_DETACHED": 1,
	"OT_DEVICE_ROLE_CHILD":    2,
	"OT_DEVICE_ROLE_ROUTER":   3,
	"OT_DEVICE_ROLE_LEADER":   4,
}

func (x OtDeviceRole) String() string {
	return proto.EnumName(OtDeviceRole_name, int32(x))
}

func (OtDeviceRole) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2d9802f2a4ce48dd, []int{0}
}

type VisualizeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VisualizeRequest) Reset()         { *m = VisualizeRequest{} }
func (m *VisualizeRequest) String() string { return proto.CompactTextString(m) }
func (*VisualizeRequest) ProtoMessage()    {}
func (*VisualizeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d9802f2a4ce48dd, []int{0}
}

func (m *VisualizeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VisualizeRequest.Unmarshal(m, b)
}
func (m *VisualizeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VisualizeRequest.Marshal(b, m, deterministic)
}
func (m *VisualizeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VisualizeRequest.Merge(m, src)
}
func (m *VisualizeRequest) XXX_Size() int {
	return xxx_messageInfo_VisualizeRequest.Size(m)
}
func (m *VisualizeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VisualizeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VisualizeRequest proto.InternalMessageInfo

type VisualizeEvent struct {
	// Types that are valid to be assigned to Type:
	//	*VisualizeEvent_AddNode
	//	*VisualizeEvent_DeleteNode
	//	*VisualizeEvent_SetNodeRloc16
	//	*VisualizeEvent_SetNodeRole
	//	*VisualizeEvent_SetNodePos
	//	*VisualizeEvent_SetNodePartitionId
	//	*VisualizeEvent_OnNodeFail
	//	*VisualizeEvent_OnNodeRecover
	//	*VisualizeEvent_SetParent
	//	*VisualizeEvent_CountDown
	//	*VisualizeEvent_ShowDemoLegend
	//	*VisualizeEvent_AdvanceTime
	//	*VisualizeEvent_AddRouterTable
	//	*VisualizeEvent_RemoveRouterTable
	//	*VisualizeEvent_AddChildTable
	//	*VisualizeEvent_RemoveChildTable
	//	*VisualizeEvent_Send
	//	*VisualizeEvent_SetSpeed
	//	*VisualizeEvent_Heartbeat
	//	*VisualizeEvent_OnExtAddrChange
	Type                 isVisualizeEvent_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *VisualizeEvent) Reset()         { *m = VisualizeEvent{} }
func (m *VisualizeEvent) String() string { return proto.CompactTextString(m) }
func (*VisualizeEvent) ProtoMessage()    {}
func (*VisualizeEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d9802f2a4ce48dd, []int{1}
}

func (m *VisualizeEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VisualizeEvent.Unmarshal(m, b)
}
func (m *VisualizeEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VisualizeEvent.Marshal(b, m, deterministic)
}
func (m *VisualizeEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VisualizeEvent.Merge(m, src)
}
func (m *VisualizeEvent) XXX_Size() int {
	return xxx_messageInfo_VisualizeEvent.Size(m)
}
func (m *VisualizeEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_VisualizeEvent.DiscardUnknown(m)
}

var xxx_messageInfo_VisualizeEvent proto.InternalMessageInfo

type isVisualizeEvent_Type interface {
	isVisualizeEvent_Type()
}

type VisualizeEvent_AddNode struct {
	AddNode *AddNodeEvent `protobuf:"bytes,1,opt,name=add_node,json=addNode,proto3,oneof"`
}

type VisualizeEvent_DeleteNode struct {
	DeleteNode *DeleteNodeEvent `protobuf:"bytes,2,opt,name=delete_node,json=deleteNode,proto3,oneof"`
}

type VisualizeEvent_SetNodeRloc16 struct {
	SetNodeRloc16 *SetNodeRloc16Event `protobuf:"bytes,3,opt,name=set_node_rloc16,json=setNodeRloc16,proto3,oneof"`
}

type VisualizeEvent_SetNodeRole struct {
	SetNodeRole *SetNodeRoleEvent `protobuf:"bytes,4,opt,name=set_node_role,json=setNodeRole,proto3,oneof"`
}

type VisualizeEvent_SetNodePos struct {
	SetNodePos *SetNodePosEvent `protobuf:"bytes,5,opt,name=set_node_pos,json=setNodePos,proto3,oneof"`
}

type VisualizeEvent_SetNodePartitionId struct {
	SetNodePartitionId *SetNodePartitionIdEvent `protobuf:"bytes,6,opt,name=set_node_partition_id,json=setNodePartitionId,proto3,oneof"`
}

type VisualizeEvent_OnNodeFail struct {
	OnNodeFail *OnNodeFailEvent `protobuf:"bytes,7,opt,name=on_node_fail,json=onNodeFail,proto3,oneof"`
}

type VisualizeEvent_OnNodeRecover struct {
	OnNodeRecover *OnNodeRecoverEvent `protobuf:"bytes,8,opt,name=on_node_recover,json=onNodeRecover,proto3,oneof"`
}

type VisualizeEvent_SetParent struct {
	SetParent *SetParentEvent `protobuf:"bytes,9,opt,name=set_parent,json=setParent,proto3,oneof"`
}

type VisualizeEvent_CountDown struct {
	CountDown *CountDownEvent `protobuf:"bytes,10,opt,name=count_down,json=countDown,proto3,oneof"`
}

type VisualizeEvent_ShowDemoLegend struct {
	ShowDemoLegend *ShowDemoLegendEvent `protobuf:"bytes,11,opt,name=show_demo_legend,json=showDemoLegend,proto3,oneof"`
}

type VisualizeEvent_AdvanceTime struct {
	AdvanceTime *AdvanceTimeEvent `protobuf:"bytes,12,opt,name=advance_time,json=advanceTime,proto3,oneof"`
}

type VisualizeEvent_AddRouterTable struct {
	AddRouterTable *AddRouterTableEvent `protobuf:"bytes,13,opt,name=add_router_table,json=addRouterTable,proto3,oneof"`
}

type VisualizeEvent_RemoveRouterTable struct {
	RemoveRouterTable *RemoveRouterTableEvent `protobuf:"bytes,14,opt,name=remove_router_table,json=removeRouterTable,proto3,oneof"`
}

type VisualizeEvent_AddChildTable struct {
	AddChildTable *AddChildTableEvent `protobuf:"bytes,15,opt,name=add_child_table,json=addChildTable,proto3,oneof"`
}

type VisualizeEvent_RemoveChildTable struct {
	RemoveChildTable *RemoveChildTableEvent `protobuf:"bytes,16,opt,name=remove_child_table,json=removeChildTable,proto3,oneof"`
}

type VisualizeEvent_Send struct {
	Send *SendEvent `protobuf:"bytes,17,opt,name=send,proto3,oneof"`
}

type VisualizeEvent_SetSpeed struct {
	SetSpeed *SetSpeedEvent `protobuf:"bytes,18,opt,name=set_speed,json=setSpeed,proto3,oneof"`
}

type VisualizeEvent_Heartbeat struct {
	Heartbeat *HeartbeatEvent `protobuf:"bytes,19,opt,name=heartbeat,proto3,oneof"`
}

type VisualizeEvent_OnExtAddrChange struct {
	OnExtAddrChange *OnExtAddrChangeEvent `protobuf:"bytes,20,opt,name=on_ext_addr_change,json=onExtAddrChange,proto3,oneof"`
}

func (*VisualizeEvent_AddNode) isVisualizeEvent_Type() {}

func (*VisualizeEvent_DeleteNode) isVisualizeEvent_Type() {}

func (*VisualizeEvent_SetNodeRloc16) isVisualizeEvent_Type() {}

func (*VisualizeEvent_SetNodeRole) isVisualizeEvent_Type() {}

func (*VisualizeEvent_SetNodePos) isVisualizeEvent_Type() {}

func (*VisualizeEvent_SetNodePartitionId) isVisualizeEvent_Type() {}

func (*VisualizeEvent_OnNodeFail) isVisualizeEvent_Type() {}

func (*VisualizeEvent_OnNodeRecover) isVisualizeEvent_Type() {}

func (*VisualizeEvent_SetParent) isVisualizeEvent_Type() {}

func (*VisualizeEvent_CountDown) isVisualizeEvent_Type() {}

func (*VisualizeEvent_ShowDemoLegend) isVisualizeEvent_Type() {}

func (*VisualizeEvent_AdvanceTime) isVisualizeEvent_Type() {}

func (*VisualizeEvent_AddRouterTable) isVisualizeEvent_Type() {}

func (*VisualizeEvent_RemoveRouterTable) isVisualizeEvent_Type() {}

func (*VisualizeEvent_AddChildTable) isVisualizeEvent_Type() {}

func (*VisualizeEvent_RemoveChildTable) isVisualizeEvent_Type() {}

func (*VisualizeEvent_Send) isVisualizeEvent_Type() {}

func (*VisualizeEvent_SetSpeed) isVisualizeEvent_Type() {}

func (*VisualizeEvent_Heartbeat) isVisualizeEvent_Type() {}

func (*VisualizeEvent_OnExtAddrChange) isVisualizeEvent_Type() {}

func (m *VisualizeEvent) GetType() isVisualizeEvent_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *VisualizeEvent) GetAddNode() *AddNodeEvent {
	if x, ok := m.GetType().(*VisualizeEvent_AddNode); ok {
		return x.AddNode
	}
	return nil
}

func (m *VisualizeEvent) GetDeleteNode() *DeleteNodeEvent {
	if x, ok := m.GetType().(*VisualizeEvent_DeleteNode); ok {
		return x.DeleteNode
	}
	return nil
}

func (m *VisualizeEvent) GetSetNodeRloc16() *SetNodeRloc16Event {
	if x, ok := m.GetType().(*VisualizeEvent_SetNodeRloc16); ok {
		return x.SetNodeRloc16
	}
	return nil
}

func (m *VisualizeEvent) GetSetNodeRole() *SetNodeRoleEvent {
	if x, ok := m.GetType().(*VisualizeEvent_SetNodeRole); ok {
		return x.SetNodeRole
	}
	return nil
}

func (m *VisualizeEvent) GetSetNodePos() *SetNodePosEvent {
	if x, ok := m.GetType().(*VisualizeEvent_SetNodePos); ok {
		return x.SetNodePos
	}
	return nil
}

func (m *VisualizeEvent) GetSetNodePartitionId() *SetNodePartitionIdEvent {
	if x, ok := m.GetType().(*VisualizeEvent_SetNodePartitionId); ok {
		return x.SetNodePartitionId
	}
	return nil
}

func (m *VisualizeEvent) GetOnNodeFail() *OnNodeFailEvent {
	if x, ok := m.GetType().(*VisualizeEvent_OnNodeFail); ok {
		return x.OnNodeFail
	}
	return nil
}

func (m *VisualizeEvent) GetOnNodeRecover() *OnNodeRecoverEvent {
	if x, ok := m.GetType().(*VisualizeEvent_OnNodeRecover); ok {
		return x.OnNodeRecover
	}
	return nil
}

func (m *VisualizeEvent) GetSetParent() *SetParentEvent {
	if x, ok := m.GetType().(*VisualizeEvent_SetParent); ok {
		return x.SetParent
	}
	return nil
}

func (m *VisualizeEvent) GetCountDown() *CountDownEvent {
	if x, ok := m.GetType().(*VisualizeEvent_CountDown); ok {
		return x.CountDown
	}
	return nil
}

func (m *VisualizeEvent) GetShowDemoLegend() *ShowDemoLegendEvent {
	if x, ok := m.GetType().(*VisualizeEvent_ShowDemoLegend); ok {
		return x.ShowDemoLegend
	}
	return nil
}

func (m *VisualizeEvent) GetAdvanceTime() *AdvanceTimeEvent {
	if x, ok := m.GetType().(*VisualizeEvent_AdvanceTime); ok {
		return x.AdvanceTime
	}
	return nil
}

func (m *VisualizeEvent) GetAddRouterTable() *AddRouterTableEvent {
	if x, ok := m.GetType().(*VisualizeEvent_AddRouterTable); ok {
		return x.AddRouterTable
	}
	return nil
}

func (m *VisualizeEvent) GetRemoveRouterTable() *RemoveRouterTableEvent {
	if x, ok := m.GetType().(*VisualizeEvent_RemoveRouterTable); ok {
		return x.RemoveRouterTable
	}
	return nil
}

func (m *VisualizeEvent) GetAddChildTable() *AddChildTableEvent {
	if x, ok := m.GetType().(*VisualizeEvent_AddChildTable); ok {
		return x.AddChildTable
	}
	return nil
}

func (m *VisualizeEvent) GetRemoveChildTable() *RemoveChildTableEvent {
	if x, ok := m.GetType().(*VisualizeEvent_RemoveChildTable); ok {
		return x.RemoveChildTable
	}
	return nil
}

func (m *VisualizeEvent) GetSend() *SendEvent {
	if x, ok := m.GetType().(*VisualizeEvent_Send); ok {
		return x.Send
	}
	return nil
}

func (m *VisualizeEvent) GetSetSpeed() *SetSpeedEvent {
	if x, ok := m.GetType().(*VisualizeEvent_SetSpeed); ok {
		return x.SetSpeed
	}
	return nil
}

func (m *VisualizeEvent) GetHeartbeat() *HeartbeatEvent {
	if x, ok := m.GetType().(*VisualizeEvent_Heartbeat); ok {
		return x.Heartbeat
	}
	return nil
}

func (m *VisualizeEvent) GetOnExtAddrChange() *OnExtAddrChangeEvent {
	if x, ok := m.GetType().(*VisualizeEvent_OnExtAddrChange); ok {
		return x.OnExtAddrChange
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*VisualizeEvent) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*VisualizeEvent_AddNode)(nil),
		(*VisualizeEvent_DeleteNode)(nil),
		(*VisualizeEvent_SetNodeRloc16)(nil),
		(*VisualizeEvent_SetNodeRole)(nil),
		(*VisualizeEvent_SetNodePos)(nil),
		(*VisualizeEvent_SetNodePartitionId)(nil),
		(*VisualizeEvent_OnNodeFail)(nil),
		(*VisualizeEvent_OnNodeRecover)(nil),
		(*VisualizeEvent_SetParent)(nil),
		(*VisualizeEvent_CountDown)(nil),
		(*VisualizeEvent_ShowDemoLegend)(nil),
		(*VisualizeEvent_AdvanceTime)(nil),
		(*VisualizeEvent_AddRouterTable)(nil),
		(*VisualizeEvent_RemoveRouterTable)(nil),
		(*VisualizeEvent_AddChildTable)(nil),
		(*VisualizeEvent_RemoveChildTable)(nil),
		(*VisualizeEvent_Send)(nil),
		(*VisualizeEvent_SetSpeed)(nil),
		(*VisualizeEvent_Heartbeat)(nil),
		(*VisualizeEvent_OnExtAddrChange)(nil),
	}
}

type SendEvent struct {
	SrcId                int32             `protobuf:"varint,1,opt,name=src_id,json=srcId,proto3" json:"src_id,omitempty"`
	DstId                int32             `protobuf:"varint,2,opt,name=dst_id,json=dstId,proto3" json:"dst_id,omitempty"`
	MvInfo               *MsgVisualizeInfo `protobuf:"bytes,3,opt,name=mv_info,json=mvInfo,proto3" json:"mv_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SendEvent) Reset()         { *m = SendEvent{} }
func (m *SendEvent) String() string { return proto.CompactTextString(m) }
func (*SendEvent) ProtoMessage()    {}
func (*SendEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d9802f2a4ce48dd, []int{2}
}

func (m *SendEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEvent.Unmarshal(m, b)
}
func (m *SendEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEvent.Marshal(b, m, deterministic)
}
func (m *SendEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEvent.Merge(m, src)
}
func (m *SendEvent) XXX_Size() int {
	return xxx_messageInfo_SendEvent.Size(m)
}
func (m *SendEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEvent.DiscardUnknown(m)
}

var xxx_messageInfo_SendEvent proto.InternalMessageInfo

func (m *SendEvent) GetSrcId() int32 {
	if m != nil {
		return m.SrcId
	}
	return 0
}

func (m *SendEvent) GetDstId() int32 {
	if m != nil {
		return m.DstId
	}
	return 0
}

func (m *SendEvent) GetMvInfo() *MsgVisualizeInfo {
	if m != nil {
		return m.MvInfo
	}
	return nil
}

type MsgVisualizeInfo struct {
	Channel              uint32   `protobuf:"varint,1,opt,name=channel,proto3" json:"channel,omitempty"`
	FrameControl         uint32   `protobuf:"varint,2,opt,name=frame_control,json=frameControl,proto3" json:"frame_control,omitempty"`
	Seq                  uint32   `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	DstAddrShort         uint32   `protobuf:"varint,4,opt,name=dst_addr_short,json=dstAddrShort,proto3" json:"dst_addr_short,omitempty"`
	DstAddrExtended      uint64   `protobuf:"varint,5,opt,name=dst_addr_extended,json=dstAddrExtended,proto3" json:"dst_addr_extended,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgVisualizeInfo) Reset()         { *m = MsgVisualizeInfo{} }
func (m *MsgVisualizeInfo) String() string { return proto.CompactTextString(m) }
func (*MsgVisualizeInfo) ProtoMessage()    {}
func (*MsgVisualizeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d9802f2a4ce48dd, []int{3}
}

func (m *MsgVisualizeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgVisualizeInfo.Unmarshal(m, b)
}
func (m *MsgVisualizeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgVisualizeInfo.Marshal(b, m, deterministic)
}
func (m *MsgVisualizeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgVisualizeInfo.Merge(m, src)
}
func (m *MsgVisualizeInfo) XXX_Size() int {
	return xxx_messageInfo_MsgVisualizeInfo.Size(m)
}
func (m *MsgVisualizeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgVisualizeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MsgVisualizeInfo proto.InternalMessageInfo

func (m *MsgVisualizeInfo) GetChannel() uint32 {
	if m != nil {
		return m.Channel
	}
	return 0
}

func (m *MsgVisualizeInfo) GetFrameControl() uint32 {
	if m != nil {
		return m.FrameControl
	}
	return 0
}

func (m *MsgVisualizeInfo) GetSeq() uint32 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *MsgVisualizeInfo) GetDstAddrShort() uint32 {
	if m != nil {
		return m.DstAddrShort
	}
	return 0
}

func (m *MsgVisualizeInfo) GetDstAddrExtended() uint64 {
	if m != nil {
		return m.DstAddrExtended
	}
	return 0
}

type AddRouterTableEvent struct {
	NodeId               int32    `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ExtAddr              uint64   `protobuf:"varint,2,opt,name=ext_addr,json=extAddr,proto3" json:"ext_addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRouterTableEvent) Reset()         { *m = AddRouterTableEvent{} }
func (m *AddRouterTableEvent) String() string { return proto.CompactTextString(m) }
func (*AddRouterTableEvent) ProtoMessage()    {}
func (*AddRouterTableEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d9802f2a4ce48dd, []int{4}
}

func (m *AddRouterTableEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRouterTableEvent.Unmarshal(m, b)
}
func (m *AddRouterTableEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRouterTableEvent.Marshal(b, m, deterministic)
}
func (m *AddRouterTableEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRouterTableEvent.Merge(m, src)
}
func (m *AddRouterTableEvent) XXX_Size() int {
	return xxx_messageInfo_AddRouterTableEvent.Size(m)
}
func (m *AddRouterTableEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRouterTableEvent.DiscardUnknown(m)
}

var xxx_messageInfo_AddRouterTableEvent proto.InternalMessageInfo

func (m *AddRouterTableEvent) GetNodeId() int32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *AddRouterTableEvent) GetExtAddr() uint64 {
	if m != nil {
		return m.ExtAddr
	}
	return 0
}

type RemoveRouterTableEvent struct {
	NodeId               int32    `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ExtAddr              uint64   `protobuf:"varint,2,opt,name=ext_addr,json=extAddr,proto3" json:"ext_addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveRouterTableEvent) Reset()         { *m = RemoveRouterTableEvent{} }
func (m *RemoveRouterTableEvent) String() string { return proto.CompactTextString(m) }
func (*RemoveRouterTableEvent) ProtoMessage()    {}
func (*RemoveRouterTableEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d9802f2a4ce48dd, []int{5}
}

func (m *RemoveRouterTableEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveRouterTableEvent.Unmarshal(m, b)
}
func (m *RemoveRouterTableEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveRouterTableEvent.Marshal(b, m, deterministic)
}
func (m *RemoveRouterTableEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveRouterTableEvent.Merge(m, src)
}
func (m *RemoveRouterTableEvent) XXX_Size() int {
	return xxx_messageInfo_RemoveRouterTableEvent.Size(m)
}
func (m *RemoveRouterTableEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveRouterTableEvent.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveRouterTableEvent proto.InternalMessageInfo

func (m *RemoveRouterTableEvent) GetNodeId() int32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *RemoveRouterTableEvent) GetExtAddr() uint64 {
	if m != nil {
		return m.ExtAddr
	}
	return 0
}

type AddChildTableEvent struct {
	NodeId               int32    `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ExtAddr              uint64   `protobuf:"varint,2,opt,name=ext_addr,json=extAddr,proto3" json:"ext_addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddChildTableEvent) Reset()         { *m = AddChildTableEvent{} }
func (m *AddChildTableEvent) String() string { return proto.CompactTextString(m) }
func (*AddChildTableEvent) ProtoMessage()    {}
func (*AddChildTableEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d9802f2a4ce48dd, []int{6}
}

func (m *AddChildTableEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddChildTableEvent.Unmarshal(m, b)
}
func (m *AddChildTableEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddChildTableEvent.Marshal(b, m, deterministic)
}
func (m *AddChildTableEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddChildTableEvent.Merge(m, src)
}
func (m *AddChildTableEvent) XXX_Size() int {
	return xxx_messageInfo_AddChildTableEvent.Size(m)
}
func (m *AddChildTableEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_AddChildTableEvent.DiscardUnknown(m)
}

var xxx_messageInfo_AddChildTableEvent proto.InternalMessageInfo

func (m *AddChildTableEvent) GetNodeId() int32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *AddChildTableEvent) GetExtAddr() uint64 {
	if m != nil {
		return m.ExtAddr
	}
	return 0
}

type RemoveChildTableEvent struct {
	NodeId               int32    `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ExtAddr              uint64   `protobuf:"varint,2,opt,name=ext_addr,json=extAddr,proto3" json:"ext_addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveChildTableEvent) Reset()         { *m = RemoveChildTableEvent{} }
func (m *RemoveChildTableEvent) String() string { return proto.CompactTextString(m) }
func (*RemoveChildTableEvent) ProtoMessage()    {}
func (*RemoveChildTableEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d9802f2a4ce48dd, []int{7}
}

func (m *RemoveChildTableEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveChildTableEvent.Unmarshal(m, b)
}
func (m *RemoveChildTableEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveChildTableEvent.Marshal(b, m, deterministic)
}
func (m *RemoveChildTableEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveChildTableEvent.Merge(m, src)
}
func (m *RemoveChildTableEvent) XXX_Size() int {
	return xxx_messageInfo_RemoveChildTableEvent.Size(m)
}
func (m *RemoveChildTableEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveChildTableEvent.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveChildTableEvent proto.InternalMessageInfo

func (m *RemoveChildTableEvent) GetNodeId() int32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *RemoveChildTableEvent) GetExtAddr() uint64 {
	if m != nil {
		return m.ExtAddr
	}
	return 0
}

type SetSpeedEvent struct {
	Speed                float64  `protobuf:"fixed64,1,opt,name=speed,proto3" json:"speed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetSpeedEvent) Reset()         { *m = SetSpeedEvent{} }
func (m *SetSpeedEvent) String() string { return proto.CompactTextString(m) }
func (*SetSpeedEvent) ProtoMessage()    {}
func (*SetSpeedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d9802f2a4ce48dd, []int{8}
}

func (m *SetSpeedEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetSpeedEvent.Unmarshal(m, b)
}
func (m *SetSpeedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetSpeedEvent.Marshal(b, m, deterministic)
}
func (m *SetSpeedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetSpeedEvent.Merge(m, src)
}
func (m *SetSpeedEvent) XXX_Size() int {
	return xxx_messageInfo_SetSpeedEvent.Size(m)
}
func (m *SetSpeedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_SetSpeedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_SetSpeedEvent proto.InternalMessageInfo

func (m *SetSpeedEvent) GetSpeed() float64 {
	if m != nil {
		return m.Speed
	}
	return 0
}

type HeartbeatEvent struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatEvent) Reset()         { *m = HeartbeatEvent{} }
func (m *HeartbeatEvent) String() string { return proto.CompactTextString(m) }
func (*HeartbeatEvent) ProtoMessage()    {}
func (*HeartbeatEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d9802f2a4ce48dd, []int{9}
}

func (m *HeartbeatEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatEvent.Unmarshal(m, b)
}
func (m *HeartbeatEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatEvent.Marshal(b, m, deterministic)
}
func (m *HeartbeatEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatEvent.Merge(m, src)
}
func (m *HeartbeatEvent) XXX_Size() int {
	return xxx_messageInfo_HeartbeatEvent.Size(m)
}
func (m *HeartbeatEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatEvent.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatEvent proto.InternalMessageInfo

type AdvanceTimeEvent struct {
	Ts                   uint64   `protobuf:"varint,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Speed                float64  `protobuf:"fixed64,2,opt,name=speed,proto3" json:"speed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdvanceTimeEvent) Reset()         { *m = AdvanceTimeEvent{} }
func (m *AdvanceTimeEvent) String() string { return proto.CompactTextString(m) }
func (*AdvanceTimeEvent) ProtoMessage()    {}
func (*AdvanceTimeEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d9802f2a4ce48dd, []int{10}
}

func (m *AdvanceTimeEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdvanceTimeEvent.Unmarshal(m, b)
}
func (m *AdvanceTimeEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdvanceTimeEvent.Marshal(b, m, deterministic)
}
func (m *AdvanceTimeEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdvanceTimeEvent.Merge(m, src)
}
func (m *AdvanceTimeEvent) XXX_Size() int {
	return xxx_messageInfo_AdvanceTimeEvent.Size(m)
}
func (m *AdvanceTimeEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_AdvanceTimeEvent.DiscardUnknown(m)
}

var xxx_messageInfo_AdvanceTimeEvent proto.InternalMessageInfo

func (m *AdvanceTimeEvent) GetTs() uint64 {
	if m != nil {
		return m.Ts
	}
	return 0
}

func (m *AdvanceTimeEvent) GetSpeed() float64 {
	if m != nil {
		return m.Speed
	}
	return 0
}

type SetParentEvent struct {
	NodeId               int32    `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ExtAddr              uint64   `protobuf:"varint,2,opt,name=ext_addr,json=extAddr,proto3" json:"ext_addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetParentEvent) Reset()         { *m = SetParentEvent{} }
func (m *SetParentEvent) String() string { return proto.CompactTextString(m) }
func (*SetParentEvent) ProtoMessage()    {}
func (*SetParentEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d9802f2a4ce48dd, []int{11}
}

func (m *SetParentEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetParentEvent.Unmarshal(m, b)
}
func (m *SetParentEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetParentEvent.Marshal(b, m, deterministic)
}
func (m *SetParentEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetParentEvent.Merge(m, src)
}
func (m *SetParentEvent) XXX_Size() int {
	return xxx_messageInfo_SetParentEvent.Size(m)
}
func (m *SetParentEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_SetParentEvent.DiscardUnknown(m)
}

var xxx_messageInfo_SetParentEvent proto.InternalMessageInfo

func (m *SetParentEvent) GetNodeId() int32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *SetParentEvent) GetExtAddr() uint64 {
	if m != nil {
		return m.ExtAddr
	}
	return 0
}

type CountDownEvent struct {
	DurationMs           int64    `protobuf:"varint,1,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CountDownEvent) Reset()         { *m = CountDownEvent{} }
func (m *CountDownEvent) String() string { return proto.CompactTextString(m) }
func (*CountDownEvent) ProtoMessage()    {}
func (*CountDownEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d9802f2a4ce48dd, []int{12}
}

func (m *CountDownEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CountDownEvent.Unmarshal(m, b)
}
func (m *CountDownEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CountDownEvent.Marshal(b, m, deterministic)
}
func (m *CountDownEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountDownEvent.Merge(m, src)
}
func (m *CountDownEvent) XXX_Size() int {
	return xxx_messageInfo_CountDownEvent.Size(m)
}
func (m *CountDownEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_CountDownEvent.DiscardUnknown(m)
}

var xxx_messageInfo_CountDownEvent proto.InternalMessageInfo

func (m *CountDownEvent) GetDurationMs() int64 {
	if m != nil {
		return m.DurationMs
	}
	return 0
}

func (m *CountDownEvent) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type ShowDemoLegendEvent struct {
	X                    int32    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowDemoLegendEvent) Reset()         { *m = ShowDemoLegendEvent{} }
func (m *ShowDemoLegendEvent) String() string { return proto.CompactTextString(m) }
func (*ShowDemoLegendEvent) ProtoMessage()    {}
func (*ShowDemoLegendEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d9802f2a4ce48dd, []int{13}
}

func (m *ShowDemoLegendEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowDemoLegendEvent.Unmarshal(m, b)
}
func (m *ShowDemoLegendEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowDemoLegendEvent.Marshal(b, m, deterministic)
}
func (m *ShowDemoLegendEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowDemoLegendEvent.Merge(m, src)
}
func (m *ShowDemoLegendEvent) XXX_Size() int {
	return xxx_messageInfo_ShowDemoLegendEvent.Size(m)
}
func (m *ShowDemoLegendEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowDemoLegendEvent.DiscardUnknown(m)
}

var xxx_messageInfo_ShowDemoLegendEvent proto.InternalMessageInfo

func (m *ShowDemoLegendEvent) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *ShowDemoLegendEvent) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *ShowDemoLegendEvent) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type SetNodePosEvent struct {
	NodeId               int32    `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	X                    int32    `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetNodePosEvent) Reset()         { *m = SetNodePosEvent{} }
func (m *SetNodePosEvent) String() string { return proto.CompactTextString(m) }
func (*SetNodePosEvent) ProtoMessage()    {}
func (*SetNodePosEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d9802f2a4ce48dd, []int{14}
}

func (m *SetNodePosEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetNodePosEvent.Unmarshal(m, b)
}
func (m *SetNodePosEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetNodePosEvent.Marshal(b, m, deterministic)
}
func (m *SetNodePosEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetNodePosEvent.Merge(m, src)
}
func (m *SetNodePosEvent) XXX_Size() int {
	return xxx_messageInfo_SetNodePosEvent.Size(m)
}
func (m *SetNodePosEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_SetNodePosEvent.DiscardUnknown(m)
}

var xxx_messageInfo_SetNodePosEvent proto.InternalMessageInfo

func (m *SetNodePosEvent) GetNodeId() int32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *SetNodePosEvent) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *SetNodePosEvent) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type SetNodeRoleEvent struct {
	NodeId               int32        `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Role                 OtDeviceRole `protobuf:"varint,2,opt,name=role,proto3,enum=visualize_grpc_pb.OtDeviceRole" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SetNodeRoleEvent) Reset()         { *m = SetNodeRoleEvent{} }
func (m *SetNodeRoleEvent) String() string { return proto.CompactTextString(m) }
func (*SetNodeRoleEvent) ProtoMessage()    {}
func (*SetNodeRoleEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d9802f2a4ce48dd, []int{15}
}

func (m *SetNodeRoleEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetNodeRoleEvent.Unmarshal(m, b)
}
func (m *SetNodeRoleEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetNodeRoleEvent.Marshal(b, m, deterministic)
}
func (m *SetNodeRoleEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetNodeRoleEvent.Merge(m, src)
}
func (m *SetNodeRoleEvent) XXX_Size() int {
	return xxx_messageInfo_SetNodeRoleEvent.Size(m)
}
func (m *SetNodeRoleEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_SetNodeRoleEvent.DiscardUnknown(m)
}

var xxx_messageInfo_SetNodeRoleEvent proto.InternalMessageInfo

func (m *SetNodeRoleEvent) GetNodeId() int32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *SetNodeRoleEvent) GetRole() OtDeviceRole {
	if m != nil {
		return m.Role
	}
	return OtDeviceRole_OT_DEVICE_ROLE_DISABLED
}

type SetNodePartitionIdEvent struct {
	NodeId               int32    `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	PartitionId          uint32   `protobuf:"varint,2,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetNodePartitionIdEvent) Reset()         { *m = SetNodePartitionIdEvent{} }
func (m *SetNodePartitionIdEvent) String() string { return proto.CompactTextString(m) }
func (*SetNodePartitionIdEvent) ProtoMessage()    {}
func (*SetNodePartitionIdEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d9802f2a4ce48dd, []int{16}
}

func (m *SetNodePartitionIdEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetNodePartitionIdEvent.Unmarshal(m, b)
}
func (m *SetNodePartitionIdEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetNodePartitionIdEvent.Marshal(b, m, deterministic)
}
func (m *SetNodePartitionIdEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetNodePartitionIdEvent.Merge(m, src)
}
func (m *SetNodePartitionIdEvent) XXX_Size() int {
	return xxx_messageInfo_SetNodePartitionIdEvent.Size(m)
}
func (m *SetNodePartitionIdEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_SetNodePartitionIdEvent.DiscardUnknown(m)
}

var xxx_messageInfo_SetNodePartitionIdEvent proto.InternalMessageInfo

func (m *SetNodePartitionIdEvent) GetNodeId() int32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *SetNodePartitionIdEvent) GetPartitionId() uint32 {
	if m != nil {
		return m.PartitionId
	}
	return 0
}

type OnNodeFailEvent struct {
	NodeId               int32    `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnNodeFailEvent) Reset()         { *m = OnNodeFailEvent{} }
func (m *OnNodeFailEvent) String() string { return proto.CompactTextString(m) }
func (*OnNodeFailEvent) ProtoMessage()    {}
func (*OnNodeFailEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d9802f2a4ce48dd, []int{17}
}

func (m *OnNodeFailEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnNodeFailEvent.Unmarshal(m, b)
}
func (m *OnNodeFailEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnNodeFailEvent.Marshal(b, m, deterministic)
}
func (m *OnNodeFailEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnNodeFailEvent.Merge(m, src)
}
func (m *OnNodeFailEvent) XXX_Size() int {
	return xxx_messageInfo_OnNodeFailEvent.Size(m)
}
func (m *OnNodeFailEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_OnNodeFailEvent.DiscardUnknown(m)
}

var xxx_messageInfo_OnNodeFailEvent proto.InternalMessageInfo

func (m *OnNodeFailEvent) GetNodeId() int32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

type OnNodeRecoverEvent struct {
	NodeId               int32    `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnNodeRecoverEvent) Reset()         { *m = OnNodeRecoverEvent{} }
func (m *OnNodeRecoverEvent) String() string { return proto.CompactTextString(m) }
func (*OnNodeRecoverEvent) ProtoMessage()    {}
func (*OnNodeRecoverEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d9802f2a4ce48dd, []int{18}
}

func (m *OnNodeRecoverEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnNodeRecoverEvent.Unmarshal(m, b)
}
func (m *OnNodeRecoverEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnNodeRecoverEvent.Marshal(b, m, deterministic)
}
func (m *OnNodeRecoverEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnNodeRecoverEvent.Merge(m, src)
}
func (m *OnNodeRecoverEvent) XXX_Size() int {
	return xxx_messageInfo_OnNodeRecoverEvent.Size(m)
}
func (m *OnNodeRecoverEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_OnNodeRecoverEvent.DiscardUnknown(m)
}

var xxx_messageInfo_OnNodeRecoverEvent proto.InternalMessageInfo

func (m *OnNodeRecoverEvent) GetNodeId() int32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

type DeleteNodeEvent struct {
	NodeId               int32    `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteNodeEvent) Reset()         { *m = DeleteNodeEvent{} }
func (m *DeleteNodeEvent) String() string { return proto.CompactTextString(m) }
func (*DeleteNodeEvent) ProtoMessage()    {}
func (*DeleteNodeEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d9802f2a4ce48dd, []int{19}
}

func (m *DeleteNodeEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteNodeEvent.Unmarshal(m, b)
}
func (m *DeleteNodeEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteNodeEvent.Marshal(b, m, deterministic)
}
func (m *DeleteNodeEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteNodeEvent.Merge(m, src)
}
func (m *DeleteNodeEvent) XXX_Size() int {
	return xxx_messageInfo_DeleteNodeEvent.Size(m)
}
func (m *DeleteNodeEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteNodeEvent.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteNodeEvent proto.InternalMessageInfo

func (m *DeleteNodeEvent) GetNodeId() int32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

type AddNodeEvent struct {
	NodeId               int32     `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	X                    int32     `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32     `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	RadioRange           int32     `protobuf:"varint,4,opt,name=radio_range,json=radioRange,proto3" json:"radio_range,omitempty"`
	NodeMode             *NodeMode `protobuf:"bytes,5,opt,name=node_mode,json=nodeMode,proto3" json:"node_mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AddNodeEvent) Reset()         { *m = AddNodeEvent{} }
func (m *AddNodeEvent) String() string { return proto.CompactTextString(m) }
func (*AddNodeEvent) ProtoMessage()    {}
func (*AddNodeEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d9802f2a4ce48dd, []int{20}
}

func (m *AddNodeEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddNodeEvent.Unmarshal(m, b)
}
func (m *AddNodeEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddNodeEvent.Marshal(b, m, deterministic)
}
func (m *AddNodeEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddNodeEvent.Merge(m, src)
}
func (m *AddNodeEvent) XXX_Size() int {
	return xxx_messageInfo_AddNodeEvent.Size(m)
}
func (m *AddNodeEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_AddNodeEvent.DiscardUnknown(m)
}

var xxx_messageInfo_AddNodeEvent proto.InternalMessageInfo

func (m *AddNodeEvent) GetNodeId() int32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *AddNodeEvent) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *AddNodeEvent) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *AddNodeEvent) GetRadioRange() int32 {
	if m != nil {
		return m.RadioRange
	}
	return 0
}

func (m *AddNodeEvent) GetNodeMode() *NodeMode {
	if m != nil {
		return m.NodeMode
	}
	return nil
}

type NodeMode struct {
	RxOnWhenIdle         bool     `protobuf:"varint,1,opt,name=rx_on_when_idle,json=rxOnWhenIdle,proto3" json:"rx_on_when_idle,omitempty"`
	SecureDataRequests   bool     `protobuf:"varint,2,opt,name=secure_data_requests,json=secureDataRequests,proto3" json:"secure_data_requests,omitempty"`
	FullThreadDevice     bool     `protobuf:"varint,3,opt,name=full_thread_device,json=fullThreadDevice,proto3" json:"full_thread_device,omitempty"`
	FullNetworkData      bool     `protobuf:"varint,4,opt,name=full_network_data,json=fullNetworkData,proto3" json:"full_network_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeMode) Reset()         { *m = NodeMode{} }
func (m *NodeMode) String() string { return proto.CompactTextString(m) }
func (*NodeMode) ProtoMessage()    {}
func (*NodeMode) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d9802f2a4ce48dd, []int{21}
}

func (m *NodeMode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeMode.Unmarshal(m, b)
}
func (m *NodeMode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeMode.Marshal(b, m, deterministic)
}
func (m *NodeMode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeMode.Merge(m, src)
}
func (m *NodeMode) XXX_Size() int {
	return xxx_messageInfo_NodeMode.Size(m)
}
func (m *NodeMode) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeMode.DiscardUnknown(m)
}

var xxx_messageInfo_NodeMode proto.InternalMessageInfo

func (m *NodeMode) GetRxOnWhenIdle() bool {
	if m != nil {
		return m.RxOnWhenIdle
	}
	return false
}

func (m *NodeMode) GetSecureDataRequests() bool {
	if m != nil {
		return m.SecureDataRequests
	}
	return false
}

func (m *NodeMode) GetFullThreadDevice() bool {
	if m != nil {
		return m.FullThreadDevice
	}
	return false
}

func (m *NodeMode) GetFullNetworkData() bool {
	if m != nil {
		return m.FullNetworkData
	}
	return false
}

type SetNodeRloc16Event struct {
	NodeId               int32    `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Rloc16               uint32   `protobuf:"varint,2,opt,name=rloc16,proto3" json:"rloc16,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetNodeRloc16Event) Reset()         { *m = SetNodeRloc16Event{} }
func (m *SetNodeRloc16Event) String() string { return proto.CompactTextString(m) }
func (*SetNodeRloc16Event) ProtoMessage()    {}
func (*SetNodeRloc16Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d9802f2a4ce48dd, []int{22}
}

func (m *SetNodeRloc16Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetNodeRloc16Event.Unmarshal(m, b)
}
func (m *SetNodeRloc16Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetNodeRloc16Event.Marshal(b, m, deterministic)
}
func (m *SetNodeRloc16Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetNodeRloc16Event.Merge(m, src)
}
func (m *SetNodeRloc16Event) XXX_Size() int {
	return xxx_messageInfo_SetNodeRloc16Event.Size(m)
}
func (m *SetNodeRloc16Event) XXX_DiscardUnknown() {
	xxx_messageInfo_SetNodeRloc16Event.DiscardUnknown(m)
}

var xxx_messageInfo_SetNodeRloc16Event proto.InternalMessageInfo

func (m *SetNodeRloc16Event) GetNodeId() int32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *SetNodeRloc16Event) GetRloc16() uint32 {
	if m != nil {
		return m.Rloc16
	}
	return 0
}

type OnExtAddrChangeEvent struct {
	NodeId               int32    `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ExtAddr              uint64   `protobuf:"varint,2,opt,name=ext_addr,json=extAddr,proto3" json:"ext_addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnExtAddrChangeEvent) Reset()         { *m = OnExtAddrChangeEvent{} }
func (m *OnExtAddrChangeEvent) String() string { return proto.CompactTextString(m) }
func (*OnExtAddrChangeEvent) ProtoMessage()    {}
func (*OnExtAddrChangeEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d9802f2a4ce48dd, []int{23}
}

func (m *OnExtAddrChangeEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnExtAddrChangeEvent.Unmarshal(m, b)
}
func (m *OnExtAddrChangeEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnExtAddrChangeEvent.Marshal(b, m, deterministic)
}
func (m *OnExtAddrChangeEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnExtAddrChangeEvent.Merge(m, src)
}
func (m *OnExtAddrChangeEvent) XXX_Size() int {
	return xxx_messageInfo_OnExtAddrChangeEvent.Size(m)
}
func (m *OnExtAddrChangeEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_OnExtAddrChangeEvent.DiscardUnknown(m)
}

var xxx_messageInfo_OnExtAddrChangeEvent proto.InternalMessageInfo

func (m *OnExtAddrChangeEvent) GetNodeId() int32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *OnExtAddrChangeEvent) GetExtAddr() uint64 {
	if m != nil {
		return m.ExtAddr
	}
	return 0
}

type AddNodeRequest struct {
	X                    int32     `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32     `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	IsRouter             bool      `protobuf:"varint,3,opt,name=is_router,json=isRouter,proto3" json:"is_router,omitempty"`
	Mode                 *NodeMode `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"`
	NodeId               uint32    `protobuf:"varint,5,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AddNodeRequest) Reset()         { *m = AddNodeRequest{} }
func (m *AddNodeRequest) String() string { return proto.CompactTextString(m) }
func (*AddNodeRequest) ProtoMessage()    {}
func (*AddNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d9802f2a4ce48dd, []int{24}
}

func (m *AddNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddNodeRequest.Unmarshal(m, b)
}
func (m *AddNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddNodeRequest.Marshal(b, m, deterministic)
}
func (m *AddNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddNodeRequest.Merge(m, src)
}
func (m *AddNodeRequest) XXX_Size() int {
	return xxx_messageInfo_AddNodeRequest.Size(m)
}
func (m *AddNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddNodeRequest proto.InternalMessageInfo

func (m *AddNodeRequest) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *AddNodeRequest) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *AddNodeRequest) GetIsRouter() bool {
	if m != nil {
		return m.IsRouter
	}
	return false
}

func (m *AddNodeRequest) GetMode() *NodeMode {
	if m != nil {
		return m.Mode
	}
	return nil
}

func (m *AddNodeRequest) GetNodeId() uint32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

type DeleteNodeRequest struct {
	NodeId               int32    `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteNodeRequest) Reset()         { *m = DeleteNodeRequest{} }
func (m *DeleteNodeRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteNodeRequest) ProtoMessage()    {}
func (*DeleteNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d9802f2a4ce48dd, []int{25}
}

func (m *DeleteNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteNodeRequest.Unmarshal(m, b)
}
func (m *DeleteNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteNodeRequest.Marshal(b, m, deterministic)
}
func (m *DeleteNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteNodeRequest.Merge(m, src)
}
func (m *DeleteNodeRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteNodeRequest.Size(m)
}
func (m *DeleteNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteNodeRequest proto.InternalMessageInfo

func (m *DeleteNodeRequest) GetNodeId() int32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

type MoveNodeToRequest struct {
	NodeId               int32    `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	X                    int32    `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveNodeToRequest) Reset()         { *m = MoveNodeToRequest{} }
func (m *MoveNodeToRequest) String() string { return proto.CompactTextString(m) }
func (*MoveNodeToRequest) ProtoMessage()    {}
func (*MoveNodeToRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d9802f2a4ce48dd, []int{26}
}

func (m *MoveNodeToRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveNodeToRequest.Unmarshal(m, b)
}
func (m *MoveNodeToRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveNodeToRequest.Marshal(b, m, deterministic)
}
func (m *MoveNodeToRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveNodeToRequest.Merge(m, src)
}
func (m *MoveNodeToRequest) XXX_Size() int {
	return xxx_messageInfo_MoveNodeToRequest.Size(m)
}
func (m *MoveNodeToRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveNodeToRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MoveNodeToRequest proto.InternalMessageInfo

func (m *MoveNodeToRequest) GetNodeId() int32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *MoveNodeToRequest) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *MoveNodeToRequest) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type SetNodeFailedRequest struct {
	NodeId               int32    `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Failed               bool     `protobuf:"varint,2,opt,name=failed,proto3" json:"failed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetNodeFailedRequest) Reset()         { *m = SetNodeFailedRequest{} }
func (m *SetNodeFailedRequest) String() string { return proto.CompactTextString(m) }
func (*SetNodeFailedRequest) ProtoMessage()    {}
func (*SetNodeFailedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d9802f2a4ce48dd, []int{27}
}

func (m *SetNodeFailedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetNodeFailedRequest.Unmarshal(m, b)
}
func (m *SetNodeFailedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetNodeFailedRequest.Marshal(b, m, deterministic)
}
func (m *SetNodeFailedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetNodeFailedRequest.Merge(m, src)
}
func (m *SetNodeFailedRequest) XXX_Size() int {
	return xxx_messageInfo_SetNodeFailedRequest.Size(m)
}
func (m *SetNodeFailedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetNodeFailedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetNodeFailedRequest proto.InternalMessageInfo

func (m *SetNodeFailedRequest) GetNodeId() int32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *SetNodeFailedRequest) GetFailed() bool {
	if m != nil {
		return m.Failed
	}
	return false
}

type SetSpeedRequest struct {
	Speed                float64  `protobuf:"fixed64,1,opt,name=speed,proto3" json:"speed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetSpeedRequest) Reset()         { *m = SetSpeedRequest{} }
func (m *SetSpeedRequest) String() string { return proto.CompactTextString(m) }
func (*SetSpeedRequest) ProtoMessage()    {}
func (*SetSpeedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d9802f2a4ce48dd, []int{28}
}

func (m *SetSpeedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetSpeedRequest.Unmarshal(m, b)
}
func (m *SetSpeedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetSpeedRequest.Marshal(b, m, deterministic)
}
func (m *SetSpeedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetSpeedRequest.Merge(m, src)
}
func (m *SetSpeedRequest) XXX_Size() int {
	return xxx_messageInfo_SetSpeedRequest.Size(m)
}
func (m *SetSpeedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetSpeedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetSpeedRequest proto.InternalMessageInfo

func (m *SetSpeedRequest) GetSpeed() float64 {
	if m != nil {
		return m.Speed
	}
	return 0
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d9802f2a4ce48dd, []int{29}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("visualize_grpc_pb.OtDeviceRole", OtDeviceRole_name, OtDeviceRole_value)
	proto.RegisterType((*VisualizeRequest)(nil), "visualize_grpc_pb.VisualizeRequest")
	proto.RegisterType((*VisualizeEvent)(nil), "visualize_grpc_pb.VisualizeEvent")
	proto.RegisterType((*SendEvent)(nil), "visualize_grpc_pb.SendEvent")
	proto.RegisterType((*MsgVisualizeInfo)(nil), "visualize_grpc_pb.MsgVisualizeInfo")
	proto.RegisterType((*AddRouterTableEvent)(nil), "visualize_grpc_pb.AddRouterTableEvent")
	proto.RegisterType((*RemoveRouterTableEvent)(nil), "visualize_grpc_pb.RemoveRouterTableEvent")
	proto.RegisterType((*AddChildTableEvent)(nil), "visualize_grpc_pb.AddChildTableEvent")
	proto.RegisterType((*RemoveChildTableEvent)(nil), "visualize_grpc_pb.RemoveChildTableEvent")
	proto.RegisterType((*SetSpeedEvent)(nil), "visualize_grpc_pb.SetSpeedEvent")
	proto.RegisterType((*HeartbeatEvent)(nil), "visualize_grpc_pb.HeartbeatEvent")
	proto.RegisterType((*AdvanceTimeEvent)(nil), "visualize_grpc_pb.AdvanceTimeEvent")
	proto.RegisterType((*SetParentEvent)(nil), "visualize_grpc_pb.SetParentEvent")
	proto.RegisterType((*CountDownEvent)(nil), "visualize_grpc_pb.CountDownEvent")
	proto.RegisterType((*ShowDemoLegendEvent)(nil), "visualize_grpc_pb.ShowDemoLegendEvent")
	proto.RegisterType((*SetNodePosEvent)(nil), "visualize_grpc_pb.SetNodePosEvent")
	proto.RegisterType((*SetNodeRoleEvent)(nil), "visualize_grpc_pb.SetNodeRoleEvent")
	proto.RegisterType((*SetNodePartitionIdEvent)(nil), "visualize_grpc_pb.SetNodePartitionIdEvent")
	proto.RegisterType((*OnNodeFailEvent)(nil), "visualize_grpc_pb.OnNodeFailEvent")
	proto.RegisterType((*OnNodeRecoverEvent)(nil), "visualize_grpc_pb.OnNodeRecoverEvent")
	proto.RegisterType((*DeleteNodeEvent)(nil), "visualize_grpc_pb.DeleteNodeEvent")
	proto.RegisterType((*AddNodeEvent)(nil), "visualize_grpc_pb.AddNodeEvent")
	proto.RegisterType((*NodeMode)(nil), "visualize_grpc_pb.NodeMode")
	proto.RegisterType((*SetNodeRloc16Event)(nil), "visualize_grpc_pb.SetNodeRloc16Event")
	proto.RegisterType((*OnExtAddrChangeEvent)(nil), "visualize_grpc_pb.OnExtAddrChangeEvent")
	proto.RegisterType((*AddNodeRequest)(nil), "visualize_grpc_pb.AddNodeRequest")
	proto.RegisterType((*DeleteNodeRequest)(nil), "visualize_grpc_pb.DeleteNodeRequest")
	proto.RegisterType((*MoveNodeToRequest)(nil), "visualize_grpc_pb.MoveNodeToRequest")
	proto.RegisterType((*SetNodeFailedRequest)(nil), "visualize_grpc_pb.SetNodeFailedRequest")
	proto.RegisterType((*SetSpeedRequest)(nil), "visualize_grpc_pb.SetSpeedRequest")
	proto.RegisterType((*Empty)(nil), "visualize_grpc_pb.Empty")
}

func init() {
	proto.RegisterFile("visualize_grpc.proto", fileDescriptor_2d9802f2a4ce48dd)
}

var fileDescriptor_2d9802f2a4ce48dd = []byte{
	// 1504 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x98, 0x4b, 0x73, 0xdb, 0xb6,
	0x16, 0xc7, 0x23, 0x5b, 0x96, 0xa5, 0x63, 0x3d, 0x68, 0x58, 0x4e, 0x98, 0x9b, 0x3b, 0x93, 0x98,
	0x49, 0x6e, 0x72, 0x3d, 0xb9, 0xb9, 0x69, 0x32, 0xd3, 0xc9, 0x22, 0x33, 0x1d, 0x45, 0x62, 0x62,
	0xa5, 0x76, 0x9c, 0xa1, 0x1d, 0xb7, 0x33, 0x5d, 0xb0, 0xb4, 0x00, 0x5b, 0x9c, 0x52, 0x84, 0x02,
	0xc0, 0xb2, 0xdc, 0x6d, 0xd7, 0x5d, 0x75, 0xd3, 0x55, 0xbf, 0x45, 0x97, 0xfd, 0x6e, 0x1d, 0x1c,
	0x3e, 0xf4, 0x22, 0xe5, 0x8e, 0x57, 0x16, 0xfe, 0xf8, 0xf3, 0xc7, 0x03, 0xe0, 0x00, 0x38, 0x34,
	0x34, 0x47, 0xbe, 0xbc, 0xf0, 0x02, 0xff, 0x67, 0xe6, 0x9e, 0x8b, 0x61, 0xef, 0xf9, 0x50, 0x70,
	0xc5, 0xc9, 0xe6, 0xac, 0xea, 0x0e, 0x4f, 0x2d, 0x02, 0xc6, 0x49, 0x22, 0x3a, 0xec, 0xcb, 0x05,
	0x93, 0xca, 0xfa, 0xb5, 0x0a, 0xf5, 0x54, 0xb4, 0x47, 0x2c, 0x54, 0xe4, 0x0d, 0x94, 0x3d, 0x4a,
	0xdd, 0x90, 0x53, 0x66, 0x16, 0x1e, 0x14, 0x9e, 0x6e, 0xbc, 0xbc, 0xff, 0x7c, 0x01, 0xf6, 0xbc,
	0x45, 0xe9, 0x47, 0x4e, 0xa3, 0x47, 0xf6, 0x6e, 0x39, 0xeb, 0x5e, 0xd4, 0x26, 0x36, 0x6c, 0x50,
	0x16, 0x30, 0xc5, 0x22, 0xc0, 0x0a, 0x02, 0xac, 0x0c, 0x40, 0x07, 0x5d, 0xd3, 0x0c, 0xa0, 0xa9,
	0x44, 0x0e, 0xa1, 0x21, 0x99, 0x42, 0x86, 0x2b, 0x02, 0xde, 0xfb, 0xea, 0x6b, 0x73, 0x15, 0x51,
	0x8f, 0x33, 0x50, 0x47, 0x4c, 0xe9, 0x87, 0x1c, 0xf4, 0x25, 0xb4, 0x9a, 0x9c, 0x56, 0x49, 0x17,
	0x6a, 0x13, 0x20, 0x0f, 0x98, 0x59, 0x44, 0xdc, 0xc3, 0x25, 0x38, 0x1e, 0xa4, 0xa1, 0x6d, 0xc8,
	0x89, 0x46, 0xde, 0x41, 0x35, 0x45, 0x0d, 0xb9, 0x34, 0xd7, 0x72, 0xc7, 0x18, 0x93, 0x3e, 0x71,
	0x99, 0x8e, 0x51, 0xa6, 0x12, 0x71, 0x61, 0x7b, 0xc2, 0xf1, 0x84, 0xf2, 0x95, 0xcf, 0x43, 0xd7,
	0xa7, 0x66, 0x09, 0x81, 0xbb, 0x4b, 0x80, 0x89, 0xbb, 0x4b, 0x13, 0x30, 0x91, 0x0b, 0x5d, 0x3a,
	0x50, 0x1e, 0x46, 0xfc, 0x33, 0xcf, 0x0f, 0xcc, 0xf5, 0xdc, 0x40, 0x0f, 0x43, 0xfd, 0xec, 0x3b,
	0xcf, 0x0f, 0xd2, 0x40, 0x79, 0x2a, 0xe9, 0xc5, 0x48, 0x38, 0x82, 0xf5, 0xf8, 0x88, 0x09, 0xb3,
	0x9c, 0xbb, 0x18, 0x11, 0xca, 0x89, 0x7c, 0xe9, 0x62, 0xf0, 0x69, 0x95, 0xbc, 0x05, 0x3d, 0x0f,
	0x7a, 0xd0, 0x2c, 0x54, 0x66, 0x05, 0x59, 0x3b, 0xd9, 0xc3, 0xfd, 0x84, 0x9e, 0x84, 0x53, 0x91,
	0x89, 0xa2, 0x19, 0x3d, 0x7e, 0x11, 0x2a, 0x97, 0xf2, 0xcb, 0xd0, 0x84, 0x5c, 0x46, 0x5b, 0x9b,
	0x3a, 0xfc, 0x32, 0x4c, 0x19, 0xbd, 0x44, 0x21, 0x0e, 0x18, 0xb2, 0xcf, 0x2f, 0x5d, 0xca, 0x06,
	0xdc, 0x0d, 0xd8, 0x39, 0x0b, 0xa9, 0xb9, 0x81, 0xa4, 0xff, 0x64, 0x45, 0xd3, 0xe7, 0x97, 0x1d,
	0x36, 0xe0, 0xfb, 0x68, 0x4c, 0x70, 0x75, 0x39, 0x23, 0x93, 0x3d, 0xa8, 0x7a, 0x74, 0xe4, 0x85,
	0x3d, 0xe6, 0x2a, 0x7f, 0xc0, 0xcc, 0x6a, 0x6e, 0x9e, 0xb5, 0x22, 0xdb, 0xb1, 0x3f, 0x98, 0xe4,
	0x99, 0x37, 0xd1, 0x74, 0x74, 0x7a, 0x23, 0x0a, 0x7e, 0xa1, 0x98, 0x70, 0x95, 0x77, 0x1a, 0x30,
	0xb3, 0x96, 0x1b, 0x5d, 0x8b, 0x52, 0x07, 0x9d, 0xc7, 0xda, 0x98, 0x46, 0xe7, 0xcd, 0xc8, 0xe4,
	0x07, 0xd8, 0x12, 0x6c, 0xc0, 0x47, 0x6c, 0x16, 0x5b, 0x47, 0xec, 0x7f, 0x33, 0xb0, 0x0e, 0xba,
	0x33, 0xc8, 0x9b, 0x62, 0xbe, 0x47, 0xe7, 0x89, 0x0e, 0xb8, 0xd7, 0xf7, 0x03, 0x1a, 0x83, 0x1b,
	0xb9, 0x79, 0xd2, 0xa2, 0xb4, 0xad, 0x8d, 0x33, 0xd0, 0x9a, 0x37, 0xad, 0x92, 0xef, 0x81, 0xc4,
	0xd1, 0x4e, 0x33, 0x0d, 0x64, 0x3e, 0xcd, 0x0d, 0x76, 0x11, 0x6b, 0x88, 0xb9, 0x0e, 0xf2, 0x12,
	0x8a, 0x52, 0xaf, 0xf6, 0x26, 0xb2, 0xfe, 0x9d, 0x99, 0x7b, 0x93, 0x35, 0x46, 0x2f, 0xf9, 0x06,
	0x74, 0xfa, 0xb9, 0x72, 0xc8, 0x18, 0x35, 0x09, 0x3e, 0xf8, 0x20, 0x3b, 0x69, 0x8f, 0xb4, 0x25,
	0x79, 0xb8, 0x2c, 0x63, 0x81, 0xb4, 0xa0, 0xd2, 0x67, 0x9e, 0x50, 0xa7, 0xcc, 0x53, 0xe6, 0x56,
	0x6e, 0xc6, 0xee, 0x25, 0x9e, 0x34, 0x63, 0xd3, 0xa7, 0xc8, 0x09, 0x10, 0x1e, 0xba, 0x6c, 0xac,
	0x5c, 0x8f, 0x52, 0xe1, 0xf6, 0xfa, 0x5e, 0x78, 0xce, 0xcc, 0x26, 0xb2, 0x9e, 0x64, 0xee, 0x46,
	0x7b, 0xac, 0x5a, 0x94, 0x8a, 0x36, 0x3a, 0x13, 0x62, 0x83, 0xcf, 0xea, 0x6f, 0x4b, 0x50, 0x54,
	0x57, 0x43, 0x66, 0x5d, 0x42, 0x25, 0x1d, 0x38, 0xd9, 0x86, 0x92, 0x14, 0x3d, 0x7d, 0x22, 0xe9,
	0x7b, 0x60, 0xcd, 0x59, 0x93, 0xa2, 0xd7, 0xa5, 0x5a, 0xa6, 0x52, 0x69, 0x79, 0x25, 0x92, 0xa9,
	0x54, 0x5d, 0x4a, 0xde, 0xc0, 0xfa, 0x60, 0xe4, 0xfa, 0xe1, 0x19, 0x8f, 0x8f, 0xea, 0xac, 0x9c,
	0x3f, 0x90, 0xe7, 0xe9, 0x75, 0xd3, 0x0d, 0xcf, 0xb8, 0x53, 0x1a, 0x8c, 0xf4, 0x5f, 0xeb, 0xcf,
	0x02, 0x18, 0xf3, 0x9d, 0xc4, 0x84, 0x75, 0x3d, 0xc2, 0x90, 0x05, 0x18, 0x41, 0xcd, 0x49, 0x9a,
	0xe4, 0x21, 0xd4, 0xce, 0x84, 0x37, 0x60, 0x6e, 0x8f, 0x87, 0x4a, 0xf0, 0x00, 0x43, 0xa9, 0x39,
	0x55, 0x14, 0xdb, 0x91, 0x46, 0x0c, 0x58, 0x95, 0xec, 0x0b, 0x46, 0x53, 0x73, 0xf4, 0x4f, 0xf2,
	0x08, 0xea, 0x3a, 0x74, 0x9c, 0x3b, 0xd9, 0xe7, 0x42, 0xe1, 0x35, 0x50, 0x73, 0xaa, 0x54, 0xe2,
	0x6c, 0x1c, 0x69, 0x8d, 0xec, 0xc2, 0x66, 0xea, 0x62, 0x63, 0xc5, 0x42, 0xca, 0x28, 0x9e, 0xf2,
	0x45, 0xa7, 0x11, 0x1b, 0xed, 0x58, 0xb6, 0xba, 0xb0, 0x95, 0xb1, 0xf3, 0xc8, 0x1d, 0x58, 0xc7,
	0xf3, 0x32, 0x9d, 0xbb, 0x92, 0x6e, 0x76, 0x29, 0xb9, 0x0b, 0xe5, 0x64, 0xf5, 0x30, 0xe6, 0xa2,
	0xb3, 0xce, 0xa2, 0x95, 0xb0, 0xf6, 0xe1, 0x76, 0xf6, 0x6e, 0xbb, 0x11, 0x6d, 0x0f, 0xc8, 0xe2,
	0x16, 0xbb, 0x11, 0xe9, 0x5b, 0xd8, 0xce, 0xdc, 0x58, 0x37, 0x82, 0x3d, 0x86, 0xda, 0xcc, 0x06,
	0x21, 0x4d, 0x58, 0x8b, 0x76, 0x94, 0x46, 0x14, 0x9c, 0xa8, 0x61, 0x19, 0x50, 0x9f, 0xdd, 0x06,
	0xd6, 0x6b, 0x30, 0xe6, 0x0f, 0x4c, 0x52, 0x87, 0x15, 0x25, 0xf1, 0xc1, 0xa2, 0xb3, 0xa2, 0xe4,
	0x84, 0xb5, 0x32, 0xcd, 0xea, 0x40, 0x7d, 0xf6, 0x22, 0xb9, 0x51, 0xe0, 0x36, 0xd4, 0x67, 0xaf,
	0x12, 0x72, 0x1f, 0x36, 0xe8, 0x85, 0xf0, 0xf0, 0xd6, 0x1e, 0x44, 0x61, 0xac, 0x3a, 0x90, 0x48,
	0x07, 0x92, 0x10, 0x28, 0x2a, 0x36, 0x56, 0x48, 0xaa, 0x38, 0xf8, 0xdb, 0x7a, 0x0f, 0x5b, 0x19,
	0xf7, 0x08, 0xa9, 0x42, 0x61, 0x1c, 0xc7, 0x52, 0x18, 0xeb, 0xd6, 0x55, 0xbc, 0xb9, 0x0a, 0x57,
	0x7a, 0x54, 0xca, 0x57, 0x01, 0xc3, 0x44, 0xae, 0x38, 0x51, 0xc3, 0x7a, 0x07, 0x8d, 0xb9, 0xf2,
	0x22, 0x7f, 0x58, 0x48, 0x5f, 0x99, 0xa1, 0xaf, 0xc6, 0x74, 0xeb, 0x47, 0x30, 0xe6, 0x0b, 0x9e,
	0x7c, 0xd0, 0x2b, 0x28, 0x62, 0xf1, 0xa4, 0x59, 0xf5, 0xcc, 0xba, 0xf0, 0x50, 0x75, 0xd8, 0xc8,
	0xef, 0x21, 0xcc, 0x41, 0xb3, 0xf5, 0x19, 0xee, 0xe4, 0xd4, 0x2d, 0xf9, 0x2f, 0xda, 0x81, 0xea,
	0x4c, 0x49, 0x14, 0x6d, 0xef, 0x8d, 0xe1, 0x04, 0x60, 0xed, 0x42, 0x63, 0xae, 0x6c, 0xc9, 0xc5,
	0x59, 0xff, 0x03, 0xb2, 0x58, 0x97, 0xe4, 0xdb, 0x77, 0xa1, 0x31, 0x57, 0x9e, 0xe6, 0x7b, 0xff,
	0x28, 0x40, 0x75, 0xba, 0x18, 0xbe, 0xd1, 0x2a, 0xe8, 0x5c, 0x12, 0x1e, 0xf5, 0xb9, 0x2b, 0xf0,
	0x40, 0x2f, 0xa2, 0x0e, 0x28, 0x39, 0x5a, 0x21, 0xaf, 0xa1, 0x82, 0xd4, 0x81, 0xae, 0xaa, 0xa3,
	0x8a, 0xf3, 0x5e, 0xc6, 0xf4, 0xeb, 0x30, 0x0e, 0xf4, 0x38, 0xcb, 0x61, 0xfc, 0xcb, 0xfa, 0xab,
	0x00, 0xe5, 0x44, 0x26, 0x8f, 0xa1, 0x21, 0xc6, 0x2e, 0x0f, 0xdd, 0xcb, 0x3e, 0xd3, 0x13, 0x1b,
	0x44, 0x35, 0x7e, 0xd9, 0xa9, 0x8a, 0xf1, 0x61, 0xf8, 0x5d, 0x9f, 0x85, 0x5d, 0x1a, 0x30, 0xf2,
	0x02, 0x9a, 0x92, 0xf5, 0x2e, 0x04, 0x73, 0xa9, 0xa7, 0x3c, 0x57, 0x44, 0x5f, 0x0b, 0x12, 0xa3,
	0x2f, 0xeb, 0x5a, 0x53, 0xf7, 0x75, 0x3c, 0xe5, 0xc5, 0xdf, 0x11, 0x92, 0x3c, 0x03, 0x72, 0x76,
	0x11, 0x04, 0xae, 0xea, 0x0b, 0xe6, 0x51, 0x97, 0x62, 0x12, 0xe0, 0xf8, 0xca, 0x8e, 0xa1, 0x7b,
	0x8e, 0xb1, 0x23, 0x4a, 0x0e, 0x7d, 0xc2, 0xa2, 0x3b, 0x64, 0xea, 0x92, 0x8b, 0x9f, 0xf0, 0x2d,
	0x38, 0xe8, 0xb2, 0xd3, 0xd0, 0x1d, 0x1f, 0x23, 0x5d, 0xbf, 0xc1, 0xb2, 0x81, 0x2c, 0x16, 0xf8,
	0xf9, 0xb3, 0x7c, 0x1b, 0x4a, 0xf1, 0x07, 0x43, 0x94, 0x33, 0x71, 0xcb, 0xfa, 0x00, 0xcd, 0xac,
	0xcb, 0xf0, 0x46, 0x67, 0xc1, 0x6f, 0x05, 0xa8, 0xc7, 0x6b, 0x1e, 0x4f, 0xc0, 0xd2, 0x0d, 0x7c,
	0x0f, 0x2a, 0xbe, 0x8c, 0x0b, 0xae, 0x78, 0x4a, 0xca, 0xbe, 0x8c, 0x4e, 0x79, 0xf2, 0x7f, 0x28,
	0xe2, 0x9a, 0x16, 0xaf, 0x5f, 0x53, 0x34, 0x4e, 0x07, 0xbc, 0x16, 0x8d, 0x30, 0xce, 0xc4, 0x67,
	0xb0, 0x39, 0xc9, 0xda, 0x24, 0xae, 0xdc, 0xbc, 0xdd, 0x83, 0xcd, 0x03, 0x3e, 0x42, 0xef, 0x31,
	0xbf, 0xce, 0xbd, 0xf4, 0x04, 0x79, 0x0f, 0xcd, 0x78, 0x81, 0xf4, 0x4e, 0x64, 0xf4, 0x5a, 0xd8,
	0x6d, 0x28, 0x9d, 0xa1, 0x33, 0xce, 0xa7, 0xb8, 0x65, 0x3d, 0xc1, 0x23, 0x0d, 0xef, 0x86, 0x84,
	0x91, 0x7d, 0x3b, 0xac, 0xc3, 0x9a, 0x3d, 0x18, 0xaa, 0xab, 0xdd, 0xdf, 0x0b, 0x50, 0x9d, 0x3e,
	0x71, 0xc8, 0x3d, 0xb8, 0x73, 0x78, 0xec, 0x76, 0xec, 0x93, 0x6e, 0xdb, 0x76, 0x9d, 0xc3, 0x7d,
	0xdb, 0xed, 0x74, 0x8f, 0x5a, 0x6f, 0xf7, 0xed, 0x8e, 0x71, 0x2b, 0xab, 0xd3, 0x3e, 0x6e, 0xb5,
	0xf7, 0xec, 0x8e, 0x51, 0x20, 0x26, 0x34, 0xe7, 0x3a, 0xdb, 0x7b, 0xdd, 0xfd, 0x8e, 0xb1, 0x42,
	0xee, 0xc2, 0xf6, 0x5c, 0x8f, 0x73, 0xf8, 0xf9, 0xd8, 0x76, 0x8c, 0xd5, 0x8c, 0xae, 0x7d, 0xbb,
	0xd5, 0xb1, 0x1d, 0xa3, 0xf8, 0xf2, 0x97, 0x22, 0x34, 0xd3, 0x6a, 0xe6, 0xbd, 0x18, 0xf6, 0x8e,
	0x98, 0xc0, 0xdc, 0xff, 0x0c, 0x95, 0x54, 0x27, 0x59, 0x35, 0xd2, 0xfc, 0x47, 0xfa, 0xbf, 0x76,
	0x96, 0x99, 0x30, 0x8b, 0x5f, 0x14, 0xc8, 0x07, 0xd8, 0x68, 0x2b, 0x11, 0xc4, 0x69, 0x49, 0x76,
	0xf2, 0xbf, 0xd9, 0x13, 0xac, 0x99, 0x61, 0xc1, 0x69, 0x25, 0x9f, 0xa0, 0xae, 0x59, 0x93, 0x6c,
	0x22, 0x8f, 0x96, 0x7e, 0xc1, 0xff, 0x63, 0xe2, 0x24, 0xe3, 0x32, 0x89, 0x0b, 0x09, 0xb9, 0x84,
	0x78, 0x02, 0x9b, 0x9a, 0x38, 0x93, 0x79, 0xe4, 0x49, 0xfe, 0x37, 0xf3, 0x4c, 0x6e, 0x2e, 0xe1,
	0xee, 0x43, 0x35, 0xe6, 0x46, 0x45, 0xbb, 0xb5, 0xa4, 0xc4, 0xbf, 0x96, 0x76, 0x5a, 0xc2, 0xff,
	0xc6, 0xbc, 0xfa, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xf1, 0x91, 0xf7, 0x51, 0xa5, 0x11, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// VisualizeGrpcServiceClient is the client API for VisualizeGrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VisualizeGrpcServiceClient interface {
	//    rpc Echo (EchoRequest) returns (EchoResponse);
	Visualize(ctx context.Context, in *VisualizeRequest, opts ...grpc.CallOption) (VisualizeGrpcService_VisualizeClient, error)
	CtrlAddNode(ctx context.Context, in *AddNodeRequest, opts ...grpc.CallOption) (*Empty, error)
	CtrlDeleteNode(ctx context.Context, in *DeleteNodeRequest, opts ...grpc.CallOption) (*Empty, error)
	CtrlMoveNodeTo(ctx context.Context, in *MoveNodeToRequest, opts ...grpc.CallOption) (*Empty, error)
	CtrlSetNodeFailed(ctx context.Context, in *SetNodeFailedRequest, opts ...grpc.CallOption) (*Empty, error)
	CtrlSetSpeed(ctx context.Context, in *SetSpeedRequest, opts ...grpc.CallOption) (*Empty, error)
}

type visualizeGrpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVisualizeGrpcServiceClient(cc grpc.ClientConnInterface) VisualizeGrpcServiceClient {
	return &visualizeGrpcServiceClient{cc}
}

func (c *visualizeGrpcServiceClient) Visualize(ctx context.Context, in *VisualizeRequest, opts ...grpc.CallOption) (VisualizeGrpcService_VisualizeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_VisualizeGrpcService_serviceDesc.Streams[0], "/visualize_grpc_pb.VisualizeGrpcService/Visualize", opts...)
	if err != nil {
		return nil, err
	}
	x := &visualizeGrpcServiceVisualizeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type VisualizeGrpcService_VisualizeClient interface {
	Recv() (*VisualizeEvent, error)
	grpc.ClientStream
}

type visualizeGrpcServiceVisualizeClient struct {
	grpc.ClientStream
}

func (x *visualizeGrpcServiceVisualizeClient) Recv() (*VisualizeEvent, error) {
	m := new(VisualizeEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *visualizeGrpcServiceClient) CtrlAddNode(ctx context.Context, in *AddNodeRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/visualize_grpc_pb.VisualizeGrpcService/CtrlAddNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *visualizeGrpcServiceClient) CtrlDeleteNode(ctx context.Context, in *DeleteNodeRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/visualize_grpc_pb.VisualizeGrpcService/CtrlDeleteNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *visualizeGrpcServiceClient) CtrlMoveNodeTo(ctx context.Context, in *MoveNodeToRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/visualize_grpc_pb.VisualizeGrpcService/CtrlMoveNodeTo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *visualizeGrpcServiceClient) CtrlSetNodeFailed(ctx context.Context, in *SetNodeFailedRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/visualize_grpc_pb.VisualizeGrpcService/CtrlSetNodeFailed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *visualizeGrpcServiceClient) CtrlSetSpeed(ctx context.Context, in *SetSpeedRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/visualize_grpc_pb.VisualizeGrpcService/CtrlSetSpeed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VisualizeGrpcServiceServer is the server API for VisualizeGrpcService service.
type VisualizeGrpcServiceServer interface {
	//    rpc Echo (EchoRequest) returns (EchoResponse);
	Visualize(*VisualizeRequest, VisualizeGrpcService_VisualizeServer) error
	CtrlAddNode(context.Context, *AddNodeRequest) (*Empty, error)
	CtrlDeleteNode(context.Context, *DeleteNodeRequest) (*Empty, error)
	CtrlMoveNodeTo(context.Context, *MoveNodeToRequest) (*Empty, error)
	CtrlSetNodeFailed(context.Context, *SetNodeFailedRequest) (*Empty, error)
	CtrlSetSpeed(context.Context, *SetSpeedRequest) (*Empty, error)
}

// UnimplementedVisualizeGrpcServiceServer can be embedded to have forward compatible implementations.
type UnimplementedVisualizeGrpcServiceServer struct {
}

func (*UnimplementedVisualizeGrpcServiceServer) Visualize(req *VisualizeRequest, srv VisualizeGrpcService_VisualizeServer) error {
	return status.Errorf(codes.Unimplemented, "method Visualize not implemented")
}
func (*UnimplementedVisualizeGrpcServiceServer) CtrlAddNode(ctx context.Context, req *AddNodeRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CtrlAddNode not implemented")
}
func (*UnimplementedVisualizeGrpcServiceServer) CtrlDeleteNode(ctx context.Context, req *DeleteNodeRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CtrlDeleteNode not implemented")
}
func (*UnimplementedVisualizeGrpcServiceServer) CtrlMoveNodeTo(ctx context.Context, req *MoveNodeToRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CtrlMoveNodeTo not implemented")
}
func (*UnimplementedVisualizeGrpcServiceServer) CtrlSetNodeFailed(ctx context.Context, req *SetNodeFailedRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CtrlSetNodeFailed not implemented")
}
func (*UnimplementedVisualizeGrpcServiceServer) CtrlSetSpeed(ctx context.Context, req *SetSpeedRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CtrlSetSpeed not implemented")
}

func RegisterVisualizeGrpcServiceServer(s *grpc.Server, srv VisualizeGrpcServiceServer) {
	s.RegisterService(&_VisualizeGrpcService_serviceDesc, srv)
}

func _VisualizeGrpcService_Visualize_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(VisualizeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VisualizeGrpcServiceServer).Visualize(m, &visualizeGrpcServiceVisualizeServer{stream})
}

type VisualizeGrpcService_VisualizeServer interface {
	Send(*VisualizeEvent) error
	grpc.ServerStream
}

type visualizeGrpcServiceVisualizeServer struct {
	grpc.ServerStream
}

func (x *visualizeGrpcServiceVisualizeServer) Send(m *VisualizeEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _VisualizeGrpcService_CtrlAddNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisualizeGrpcServiceServer).CtrlAddNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/visualize_grpc_pb.VisualizeGrpcService/CtrlAddNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisualizeGrpcServiceServer).CtrlAddNode(ctx, req.(*AddNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VisualizeGrpcService_CtrlDeleteNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisualizeGrpcServiceServer).CtrlDeleteNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/visualize_grpc_pb.VisualizeGrpcService/CtrlDeleteNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisualizeGrpcServiceServer).CtrlDeleteNode(ctx, req.(*DeleteNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VisualizeGrpcService_CtrlMoveNodeTo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveNodeToRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisualizeGrpcServiceServer).CtrlMoveNodeTo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/visualize_grpc_pb.VisualizeGrpcService/CtrlMoveNodeTo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisualizeGrpcServiceServer).CtrlMoveNodeTo(ctx, req.(*MoveNodeToRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VisualizeGrpcService_CtrlSetNodeFailed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetNodeFailedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisualizeGrpcServiceServer).CtrlSetNodeFailed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/visualize_grpc_pb.VisualizeGrpcService/CtrlSetNodeFailed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisualizeGrpcServiceServer).CtrlSetNodeFailed(ctx, req.(*SetNodeFailedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VisualizeGrpcService_CtrlSetSpeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSpeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisualizeGrpcServiceServer).CtrlSetSpeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/visualize_grpc_pb.VisualizeGrpcService/CtrlSetSpeed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisualizeGrpcServiceServer).CtrlSetSpeed(ctx, req.(*SetSpeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VisualizeGrpcService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "visualize_grpc_pb.VisualizeGrpcService",
	HandlerType: (*VisualizeGrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CtrlAddNode",
			Handler:    _VisualizeGrpcService_CtrlAddNode_Handler,
		},
		{
			MethodName: "CtrlDeleteNode",
			Handler:    _VisualizeGrpcService_CtrlDeleteNode_Handler,
		},
		{
			MethodName: "CtrlMoveNodeTo",
			Handler:    _VisualizeGrpcService_CtrlMoveNodeTo_Handler,
		},
		{
			MethodName: "CtrlSetNodeFailed",
			Handler:    _VisualizeGrpcService_CtrlSetNodeFailed_Handler,
		},
		{
			MethodName: "CtrlSetSpeed",
			Handler:    _VisualizeGrpcService_CtrlSetSpeed_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Visualize",
			Handler:       _VisualizeGrpcService_Visualize_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "visualize_grpc.proto",
}
