#!/bin/bash
# Copyright (c) 2020-2025, The OTNS Authors.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. Neither the name of the copyright holder nor the
#    names of its contributors may be used to endorse or promote products
#    derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# Compiles all Protocol Buffers files and gRPC interfaces

# shellcheck source=script/common.sh
. "$(dirname "$0")"/common.sh

compile_proto()
{
    cd "$OTNSDIR"/visualize/grpc/pb || return 1
    protoc -I=. visualize_grpc.proto --go_opt=paths=source_relative --go_out=plugins=grpc:.
    mkdir -p ../../../web/site/js/proto/
    protoc -I=. visualize_grpc.proto \
        --js_out=import_style=commonjs:../../../web/site/js/proto/ \
        --grpc-web_out=import_style=commonjs,mode=grpcwebtext:../../../web/site/js/proto/
    python3 -m grpc_tools.protoc -I. \
        --python_out=../../../pylibs/otns/proto \
        --grpc_python_out=../../../pylibs/otns/proto \
        ./visualize_grpc.proto
    cd - || return 1
}

replace_python_proto_import_path()
{
    local search='import visualize_grpc_pb2 as visualize__grpc__pb2'
    local replace='from . import visualize_grpc_pb2 as visualize__grpc__pb2'

    if [[ $Darwin == 1 ]]; then
        sed -i "" "s/${search}/${replace}/g" pylibs/otns/proto/visualize_grpc_pb2_grpc.py
    else
        sed -i "s/${search}/${replace}/g" pylibs/otns/proto/visualize_grpc_pb2_grpc.py
    fi
}

compile_proto
replace_python_proto_import_path
