#!/bin/bash
# Copyright (c) 2020, The OTNS Authors.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. Neither the name of the copyright holder nor the
#    names of its contributors may be used to endorse or promote products
#    derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# This script sets up the environment for OTNS development.

# shellcheck source=script/common.sh
. "$(dirname "$0")"/common.sh

PROTOBUF_VERSION=3.19.4
PROTOC_GEN_GO_VERSION=1.5.2
PROTO_GEN_GRPC_WEB_VERSION=1.3.1
GRPCIO_TOOLS_VERSION=1.43.0
GO_BINDATA_VERSION=3.0.7

skip_update='true'

while getopts ':u' 'OPTKEY'; do
    case ${OPTKEY} in
        'u')
            skip_update='false'
            ;;
        *) ;;

    esac
done

function install_protoc()
{
    local protoc_download_url

    if ${skip_update} && installed protoc; then
        return 0
    fi

    if [[ $Darwin == 1 ]]; then
        protoc_download_url=https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOBUF_VERSION}/protoc-${PROTOBUF_VERSION}-osx-x86_64.zip
    else
        protoc_download_url=https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOBUF_VERSION}/protoc-${PROTOBUF_VERSION}-linux-x86_64.zip
    fi

    wget $protoc_download_url -O /tmp/protoc.zip

    (
        cd /usr/local || return 1
        sudo unzip -o /tmp/protoc.zip
        sudo chmod a+x /usr/local/bin/protoc
        sudo rm -rf protoc.zip
    )

    installed protoc || die "protoc not found, make sure /usr/local/bin is included in $PATH"
}

install_protoc_gen_go()
{
    if ${skip_update} && installed protoc-gen-go; then
        return 0
    fi

    go_install github.com/golang/protobuf/protoc-gen-go@v${PROTOC_GEN_GO_VERSION}
    installed protoc-gen-go || die "protoc-gen-go not found, make sure $(go env GOPATH)/bin is included in $PATH"
}

install_protoc_gen_grpc_web()
{
    if ${skip_update} && installed protoc-gen-grpc-web; then
        return 0
    fi

    local download_url

    if [[ $Darwin == 1 ]]; then
        download_url=https://github.com/grpc/grpc-web/releases/download/${PROTO_GEN_GRPC_WEB_VERSION}/protoc-gen-grpc-web-${PROTO_GEN_GRPC_WEB_VERSION}-darwin-x86_64
    else
        download_url=https://github.com/grpc/grpc-web/releases/download/${PROTO_GEN_GRPC_WEB_VERSION}/protoc-gen-grpc-web-${PROTO_GEN_GRPC_WEB_VERSION}-linux-x86_64
    fi

    wget $download_url -O /tmp/protoc-gen-grpc-web
    sudo mv /tmp/protoc-gen-grpc-web /usr/local/bin/protoc-gen-grpc-web
    sudo chmod a+x /usr/local/bin/protoc-gen-grpc-web

    installed protoc-gen-grpc-web || die "protoc-gen-grpc-web not found, make sure /usr/local/bin is included in $PATH"
}

install_nodejs()
{
    if ${skip_update} && installed npm; then
        return 0
    fi

    if [[ $Darwin == 1 ]]; then
        echo "nodejs is required for OTNS-Web development. Please install from https://nodejs.org/"
    else
        sudo apt-get install nodejs npm -y
    fi
}

install_go_bindata()
{
    if ${skip_update} && installed go-bindata; then
        return 0
    fi

    go_install github.com/jteeuwen/go-bindata/go-bindata@v${GO_BINDATA_VERSION}
    installed go-bindata || die "go-bindata not found, make sure $(go env GOPATH)/bin is included in $PATH"
}

install_py_libraries()
{
    python3 -m pip install grpcio-tools==${GRPCIO_TOOLS_VERSION} --user
}

install_protoc
install_protoc_gen_go
install_protoc_gen_grpc_web
install_nodejs
install_go_bindata
install_py_libraries
install_pretty_tools || true
install_openthread_buildtools
go mod tidy
