#!/bin/bash
# Copyright (c) 2020-2022, The OTNS Authors.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. Neither the name of the copyright holder nor the
#    names of its contributors may be used to endorse or promote products
#    derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# shellcheck source=script/common.sh
. "$(dirname "$0")"/common.sh

OT_DIR=${OT_DIR:-}
OTBIN_DIR=

installed()
{
    command -v "$1" >/dev/null 2>&1
}

go_tests()
{
    install_deps
    install_otns

    build_openthread

    echo "" >coverage.txt

    PKG=$(go list ./...)

    for d in $PKG; do
        OTNS_OT_CLI=$OTBIN_DIR/ot-cli-ftd go test -race -coverprofile=profile.out -covermode=atomic -coverpkg=./... "$d"
        if [ -f profile.out ]; then
            cat profile.out >>coverage.txt
            rm profile.out
        fi
    done
}

install_deps()
{
    ./script/install-deps
}

install_otns()
{
    ./script/install
}

get_openthread()
{
    if [[ -z $OT_DIR ]]; then
        OT_DIR=$PWD/ot-rfsim
        git submodule update --init --recursive --depth 1
    fi

    OTBIN_DIR=$OT_DIR/build/bin
}

build_openthread()
{
    get_openthread

    install_openthread_buildtools

    (
        #OT_DIR=$PWD/ot-rfsim
        cd "$OT_DIR"

        # TODO: MacOS CI build fails for empty options. So we give one option here.
        local options=("-DOT_OTNS=ON")

        local COVERAGE=${COVERAGE:-0}
        if [[ $COVERAGE == 1 ]]; then
            options+=(
                "-DOT_COVERAGE=ON"
            )
        fi

        ./script/build "${options[@]}"
    )

    OT_CLI_FTD_PATH="$OTBIN_DIR/ot-cli-ftd"
    echo "Please launch OTNS with command: otns -ot-cli $OT_CLI_FTD_PATH"
}

py_unittests()
{
    install_deps
    python3 -m pip install --user -r "$OTNSDIR"/pylibs/unittests/requirements.txt
    install_otns
    build_openthread
    cd "$OTBIN_DIR"
    python3 "$OTNSDIR"/pylibs/unittests/test_basic.py
    python3 "$OTNSDIR"/pylibs/unittests/test_ping.py
    python3 "$OTNSDIR"/pylibs/unittests/test_commissioning.py
    python3 "$OTNSDIR"/pylibs/unittests/test_radiomodels.py
    python3 "$OTNSDIR"/pylibs/unittests/test_csl.py
    cd -
}

check_py_example()
{
    echo "Checking pyOTNS example: $1 ..."
    python3 "$1" &
    local pid=$!
    sleep 10
    killall otns || true
    wait $pid || die "Run pyOTNS example failed :$1"
}

py_examples()
{
    install_deps
    install_otns
    build_openthread
    cd "$OTBIN_DIR"
    check_py_example "$OTNSDIR"/pylibs/examples/simple.py
    check_py_example "$OTNSDIR"/pylibs/examples/ping.py
    check_py_example "$OTNSDIR"/pylibs/examples/farm.py
    cd -
}

test_signals()
{
    install_deps
    install_otns
    build_openthread
    cd "$OTBIN_DIR"
    python3 "$OTNSDIR"/pylibs/unittests/test_signals.py
    cd -
}

stress_tests()
{
    install_deps
    install_otns
    build_openthread
    cd "$OTBIN_DIR"
    python3 "$OTNSDIR"/pylibs/stress_tests/run_stress_suite.py "$@"
    cd -
}

main()
{
    while (("$#")); do
        case "$1" in
            go-tests)
                go_tests
                shift 1
                ;;
            py-unittests)
                py_unittests
                shift 1
                ;;
            py-examples)
                py_examples
                shift 1
                ;;
            signals)
                test_signals
                shift 1
                ;;
            stress-tests)
                stress_tests "$2"
                shift 2
                ;;
            build-openthread)
                build_openthread
                shift 1
                ;;
            *)
                echo "Error: Unsupported test $1" >&2
                return 1
                ;;
        esac
    done
}

main "$@"
